package ropgadget

import (
	"bytes"
	"compress/bzip2"
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	keystone "github.com/moloch--/go-keystone"
)

func TestSyntheticRawX86Gadgets(t *testing.T) {
	t.Parallel()

	code := assembleX86(t, keystone.MODE_32, ".code32\nnop\npop eax\nret\nxor eax, eax\nret\nint 0x80\n")
	path := writeTempBinary(t, code)

	opts := DefaultOptions()
	opts.Binary = path
	opts.RawArch = "x86"
	opts.RawMode = "32"
	opts.Depth = 5

	result, err := Analyze(context.Background(), opts)
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	texts := make([]string, 0, len(result.Gadgets))
	for _, gadget := range result.Gadgets {
		texts = append(texts, gadget.Text)
	}
	if !containsLine(texts, "ret") {
		t.Fatalf("expected a plain ret gadget, got %v", texts)
	}
	if !containsLine(texts, "pop eax ; ret") {
		t.Fatalf("expected a pop eax ; ret gadget, got %v", texts)
	}
	if !containsLine(texts, "xor eax, eax ; ret") {
		t.Fatalf("expected a xor eax, eax ; ret gadget, got %v", texts)
	}
}

func TestFixtureSearchModes(t *testing.T) {
	t.Parallel()

	x86 := fixturePath("elf-Linux-x86")
	tests := []struct {
		name string
		opts func() Options
		min  int
	}{
		{
			name: "string",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = x86
				opts.String = "main"
				return opts
			},
			min: 1,
		},
		{
			name: "opcode",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = x86
				opts.Opcode = "c9c3"
				return opts
			},
			min: 1,
		},
		{
			name: "memstr",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = x86
				opts.MemStr = "/bin/sh"
				return opts
			},
			min: 4,
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			result, err := Analyze(context.Background(), tc.opts())
			if err != nil {
				t.Fatalf("Analyze() error = %v", err)
			}
			if got := len(result.Matches); got < tc.min {
				t.Fatalf("expected at least %d matches, got %d", tc.min, got)
			}
		})
	}
}

func TestFixtureMatrixSmoke(t *testing.T) {
	cases := []struct {
		name       string
		opts       func() Options
		minCount   int
		wantPrefix []string
	}{
		{
			name: "x86-elf",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = fixturePath("elf-Linux-x86")
				opts.Depth = 3
				return opts
			},
			minCount:   8000,
			wantPrefix: []string{"ret", "jmp ", "call "},
		},
		{
			name: "armv7-elf",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = fixturePath("elf-ARMv7-ls")
				opts.Depth = 5
				return opts
			},
			minCount:   300,
			wantPrefix: []string{"bx ", "blx ", "ldm"},
		},
		{
			name: "arm64-elf",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = fixturePath("elf-ARM64-bash")
				opts.Depth = 5
				return opts
			},
			minCount:   200,
			wantPrefix: []string{"br ", "blr ", "ret"},
		},
		{
			name: "riscv64-elf",
			opts: func() Options {
				opts := DefaultOptions()
				opts.Binary = fixturePath("elf-Linux-RISCV_64")
				opts.Depth = 8
				return opts
			},
			minCount:   20,
			wantPrefix: []string{"jr ", "jalr ", "ret", "c.ret"},
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			result, err := Analyze(context.Background(), tc.opts())
			if err != nil {
				t.Fatalf("Analyze() error = %v", err)
			}
			if got := len(result.Gadgets); got < tc.minCount {
				t.Fatalf("expected at least %d gadgets, got %d", tc.minCount, got)
			}
			if !hasPrefixGadget(result.Gadgets, tc.wantPrefix...) {
				t.Fatalf("expected a gadget starting with one of %v", tc.wantPrefix)
			}
		})
	}
}

func TestROPChainGenerationX86(t *testing.T) {
	t.Parallel()

	opts := DefaultOptions()
	opts.Binary = fixturePath("elf-Linux-x86")
	opts.ROPChain = true

	result, err := Analyze(context.Background(), opts)
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	if !strings.Contains(result.ROPChain, "execve generated by ROPgadget") {
		t.Fatalf("expected a generated ROP chain, got %q", result.ROPChain)
	}
}

func TestArchivedReferenceCountSimilarityX86(t *testing.T) {
	t.Parallel()

	opts := DefaultOptions()
	opts.Binary = fixturePath("elf-Linux-x86")
	opts.Depth = 3

	result, err := Analyze(context.Background(), opts)
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	reference := referenceUniqueCount(t, "RUN elf-Linux-x86 --depth 3")
	got := len(result.Gadgets)
	lower := int(float64(reference) * 0.60)
	upper := int(float64(reference) * 1.50)
	if got < lower || got > upper {
		t.Fatalf("expected gadget count to stay within [%d, %d] around reference %d, got %d", lower, upper, reference, got)
	}
}

func TestPythonInteropWhenAvailable(t *testing.T) {
	if !pythonInteropAvailable() {
		t.Skip("python3 capstone is not installed in this environment")
	}

	opts := DefaultOptions()
	opts.Binary = fixturePath("elf-Linux-x86")
	opts.Depth = 3

	result, err := Analyze(context.Background(), opts)
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	cmd := exec.Command("python3", filepath.Join("ROPgadget", "ROPgadget.py"), "--binary", opts.Binary, "--depth", "3")
	cmd.Env = append(os.Environ(), "PYTHONPATH="+filepath.Join(".", "ROPgadget"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("python interoperability run failed: %v\n%s", err, out)
	}

	re := regexp.MustCompile(`Unique gadgets found: (\d+)`)
	matches := re.FindStringSubmatch(string(out))
	if len(matches) != 2 {
		t.Fatalf("could not parse python gadget count from output:\n%s", out)
	}
	pythonCount := atoi(t, matches[1])
	goCount := len(result.Gadgets)
	lower := int(float64(pythonCount) * 0.60)
	upper := int(float64(pythonCount) * 1.50)
	if goCount < lower || goCount > upper {
		t.Fatalf("expected Go gadget count to stay within [%d, %d] around python count %d, got %d", lower, upper, pythonCount, goCount)
	}
}

func TestCLIFlagSurface(t *testing.T) {
	t.Parallel()

	cmd := NewCommand()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"--version"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("Execute() error = %v", err)
	}
	if !strings.Contains(out.String(), VersionString()) {
		t.Fatalf("expected version output, got %q", out.String())
	}
}

func assembleX86(t *testing.T, mode keystone.Mode, src string) []byte {
	t.Helper()
	engine, err := keystone.NewEngine(keystone.ARCH_X86, mode)
	if err != nil {
		t.Fatalf("keystone.NewEngine() error = %v", err)
	}
	defer func() { _ = engine.Close() }()
	if err := engine.Option(keystone.OPT_SYNTAX, keystone.OPT_SYNTAX_INTEL); err != nil {
		t.Fatalf("engine.Option() error = %v", err)
	}
	out, err := engine.Assemble(src, 0)
	if err != nil {
		t.Fatalf("engine.Assemble() error = %v", err)
	}
	return out
}

func writeTempBinary(t *testing.T, data []byte) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "code.bin")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("os.WriteFile() error = %v", err)
	}
	return path
}

func fixturePath(name string) string {
	return filepath.Join("testdata", "test-suite-binaries", name)
}

func containsLine(lines []string, want string) bool {
	for _, line := range lines {
		if line == want {
			return true
		}
	}
	return false
}

func hasPrefixGadget(gadgets []Gadget, prefixes ...string) bool {
	for _, gadget := range gadgets {
		for _, prefix := range prefixes {
			if strings.HasPrefix(gadget.Text, prefix) {
				return true
			}
		}
	}
	return false
}

func referenceUniqueCount(t *testing.T, run string) int {
	t.Helper()
	file, err := os.Open(filepath.Join("testdata", "test-suite-binaries", "ref_output.bz2"))
	if err != nil {
		t.Fatalf("os.Open() error = %v", err)
	}
	defer file.Close()

	body, err := io.ReadAll(bzip2.NewReader(file))
	if err != nil {
		t.Fatalf("io.ReadAll() error = %v", err)
	}

	lines := strings.Split(string(body), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) != run {
			continue
		}
		for _, candidate := range lines[i+1:] {
			candidate = strings.TrimSpace(candidate)
			if strings.HasPrefix(candidate, "RUN ") {
				break
			}
			if strings.HasPrefix(candidate, "Unique gadgets found: ") {
				return atoi(t, strings.TrimPrefix(candidate, "Unique gadgets found: "))
			}
		}
	}
	t.Fatalf("reference run %q not found", run)
	return 0
}

func atoi(t *testing.T, value string) int {
	t.Helper()
	out, err := strconv.Atoi(strings.TrimSpace(value))
	if err != nil {
		t.Fatalf("strconv.Atoi(%q) error = %v", value, err)
	}
	return out
}

func pythonInteropAvailable() bool {
	cmd := exec.Command("python3", "-c", "import capstone")
	return cmd.Run() == nil
}
